# Generated by Django 3.0.5 on 2023-12-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20231222_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Supplier'),
        ),
    ]
