# Generated by Django 3.0.5 on 2023-12-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20231222_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='debit',
        ),
    ]
