# Generated by Django 5.0 on 2024-01-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_alter_activity_action_alter_drug_image_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='prescription',
        ),
    ]
