# Generated by Django 5.0 on 2024-01-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_remove_medication_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='drug',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='hospital.drug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
