# Generated by Django 5.0 on 2024-01-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_appointment_appointmenttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availableForAppointment',
            field=models.BooleanField(default=False),
        ),
    ]
