# Generated by Django 5.0 on 2024-02-07 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_alter_doctor_availableforappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='availableForAppointment',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='quantity_dispensed',
        ),
        migrations.AddField(
            model_name='medication',
            name='prescription',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='hospital.prescription'),
            preserve_default=False,
        ),
    ]
