# Generated by Django 5.0 on 2024-02-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_remove_patientdischargedetails_medicinecost'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='prescriptions',
            field=models.TextField(default='Mara Moja, All medicine tester', max_length=500),
            preserve_default=False,
        ),
    ]
