# Generated by Django 5.0 on 2024-02-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_patientdischargedetails_medicinecost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='prescriptions',
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='prescriptions',
            field=models.ManyToManyField(to='hospital.prescription'),
        ),
    ]
