# Generated by Django 5.0 on 2024-03-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0039_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentTime',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(auto_now=True),
        ),
    ]
