# Generated by Django 5.0 on 2024-03-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0043_medicalrecords_delete_medicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecords',
            name='discharge_details',
        ),
    ]
