# Generated by Django 5.0 on 2024-03-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0045_financialtransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialTransaction',
        ),
    ]
