# Generated by Django 5.0 on 2024-03-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0048_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Mara mojaaa', 'Mara mojaaa'), ('Mara mojaaa', 'Mara mojaaa'), ('sugery', 'sugery')], default='Cardiologist', max_length=50),
        ),
    ]
